# catppuccin mocha
# ref: https://github.com/catppuccin/helix
theme="catppuccin_mocha"
[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'"' = '"'

[keys.normal]
g = { a = "code_action"}

[keys.insert]
j = { j = "normal_mode"} # jj to exit insert mode

